### ISSUE TITLE
Events Not Working

### ISSUE THREAD

**Issue by northcarolinags** [bilalhassan/docs#3]
I am attempting to use the 'Events Module' within the Juno Wordpress theme.  However, I continue to receive an error message that says, "There are currently no upcoming events, please check again at a later time".  I have created events but still NOTHING!  Please help.

![screen shot 2017-02-09 at 4 20 51 pm](https://cloud.githubusercontent.com/assets/25672968/22803866/b20d59bc-eee4-11e6-9103-bf307d35bc73.png)

**Comment by smartcatdev** [comment]
@northcarolinags 
Hi there,

make sure you set the date & time of the event to ensure this runs properly. 
use the date format of yyyy-mm-dd
( see screenshot )
Link below shows how it should output.

http://juno.smartcatdev.wpengine.com/events/
![image](https://cloud.githubusercontent.com/assets/3696057/22804265/4d25fa7a-eee6-11e6-82d8-bd2a99ca720b.png)


For further support, please contact us through our website: https://smartcatdesign.net

**Comment by northcarolinags** [comment]
GREAT!  It Worked!  Is there any way to set multiple dates on an event, such as a Sunday through Friday?

**Comment by smartcatdev** [comment]
Unfortunately that's not an option, what I would suggest for that is to set the event start date on Friday and perhaps in the details mention that it's a Friday-Sunday event.

**Comment by northcarolinags** [comment]
Ok.  Thank you for your very quick response.
